/**
 * Storage abstraction. Local filesystem for development, S3-compatible object
 * storage for production (STORAGE_DRIVER=s3). Keys are always generated by the
 * server from UUIDs + sanitised segments, and are re-validated here to prevent
 * path traversal.
 */
import fs from "node:fs";
import fsp from "node:fs/promises";
import path from "node:path";
import { Readable } from "node:stream";
import { env } from "@/lib/env";

export interface StorageDriver {
  put(key: string, body: Buffer, contentType: string): Promise<void>;
  get(key: string): Promise<Buffer>;
  stream(key: string): Promise<Readable>;
  exists(key: string): Promise<boolean>;
  delete(key: string): Promise<void>;
  deletePrefix(prefix: string): Promise<void>;
}

const KEY_RE = /^[A-Za-z0-9][A-Za-z0-9._\-/]{0,400}$/;

export function assertKey(key: string): string {
  if (!KEY_RE.test(key) || key.includes("..") || key.includes("//")) {
    throw new Error("Invalid storage key");
  }
  return key;
}

class LocalDriver implements StorageDriver {
  constructor(private root: string) {}
  private p(key: string) {
    const full = path.resolve(this.root, assertKey(key));
    if (!full.startsWith(this.root + path.sep)) throw new Error("Invalid storage key");
    return full;
  }
  async put(key: string, body: Buffer) {
    const f = this.p(key);
    await fsp.mkdir(path.dirname(f), { recursive: true });
    const tmp = `${f}.${process.pid}.${Date.now()}.tmp`;
    await fsp.writeFile(tmp, body);
    await fsp.rename(tmp, f);
  }
  async get(key: string) {
    return fsp.readFile(this.p(key));
  }
  async stream(key: string) {
    return fs.createReadStream(this.p(key));
  }
  async exists(key: string) {
    try {
      await fsp.access(this.p(key));
      return true;
    } catch {
      return false;
    }
  }
  async delete(key: string) {
    await fsp.rm(this.p(key), { force: true });
  }
  async deletePrefix(prefix: string) {
    const dir = this.p(prefix.replace(/\/+$/, ""));
    await fsp.rm(dir, { recursive: true, force: true });
  }
}

class S3Driver implements StorageDriver {
  // Lazily import the SDK so local development does not need it at runtime.
  private clientP = (async () => {
    const { S3Client } = await import("@aws-sdk/client-s3");
    return new S3Client({
      region: env.s3.region,
      endpoint: env.s3.endpoint,
      forcePathStyle: env.s3.forcePathStyle,
      credentials: env.s3.accessKeyId
        ? { accessKeyId: env.s3.accessKeyId, secretAccessKey: env.s3.secretAccessKey }
        : undefined,
    });
  })();
  private bucket = env.s3.bucket;

  async put(key: string, body: Buffer, contentType: string) {
    const { PutObjectCommand } = await import("@aws-sdk/client-s3");
    const c = await this.clientP;
    await c.send(
      new PutObjectCommand({
        Bucket: this.bucket,
        Key: assertKey(key),
        Body: body,
        ContentType: contentType,
        ServerSideEncryption: "AES256",
      }),
    );
  }
  async get(key: string) {
    const s = await this.stream(key);
    const chunks: Buffer[] = [];
    for await (const ch of s) chunks.push(Buffer.from(ch as Uint8Array));
    return Buffer.concat(chunks);
  }
  async stream(key: string) {
    const { GetObjectCommand } = await import("@aws-sdk/client-s3");
    const c = await this.clientP;
    const r = await c.send(new GetObjectCommand({ Bucket: this.bucket, Key: assertKey(key) }));
    return r.Body as Readable;
  }
  async exists(key: string) {
    const { HeadObjectCommand } = await import("@aws-sdk/client-s3");
    const c = await this.clientP;
    try {
      await c.send(new HeadObjectCommand({ Bucket: this.bucket, Key: assertKey(key) }));
      return true;
    } catch {
      return false;
    }
  }
  async delete(key: string) {
    const { DeleteObjectCommand } = await import("@aws-sdk/client-s3");
    const c = await this.clientP;
    await c.send(new DeleteObjectCommand({ Bucket: this.bucket, Key: assertKey(key) }));
  }
  async deletePrefix(prefix: string) {
    const { ListObjectsV2Command, DeleteObjectsCommand } = await import("@aws-sdk/client-s3");
    const c = await this.clientP;
    let token: string | undefined;
    do {
      const list = await c.send(
        new ListObjectsV2Command({ Bucket: this.bucket, Prefix: assertKey(prefix), ContinuationToken: token }),
      );
      const objs = (list.Contents ?? []).map((o) => ({ Key: o.Key! }));
      if (objs.length) await c.send(new DeleteObjectsCommand({ Bucket: this.bucket, Delete: { Objects: objs } }));
      token = list.IsTruncated ? list.NextContinuationToken : undefined;
    } while (token);
  }
}

const g = globalThis as unknown as { __acgStorage?: StorageDriver };

export function storage(): StorageDriver {
  if (!g.__acgStorage) {
    g.__acgStorage = env.storageDriver === "s3" ? new S3Driver() : new LocalDriver(env.localStorageDir);
  }
  return g.__acgStorage;
}

export const keys = {
  asset: (orgId: string, assetId: string, ext: string) => `orgs/${orgId}/assets/${assetId}.${ext}`,
  pdf: (orgId: string, batchId: string, fileName: string) => `orgs/${orgId}/batches/${batchId}/pdf/${fileName}`,
  combined: (orgId: string, batchId: string, stamp: string) => `orgs/${orgId}/batches/${batchId}/combined/${stamp}.pdf`,
  batchPrefix: (orgId: string, batchId: string) => `orgs/${orgId}/batches/${batchId}`,
  orgPrefix: (orgId: string) => `orgs/${orgId}`,
};

export async function nodeStreamToWeb(s: Readable): Promise<ReadableStream<Uint8Array>> {
  return Readable.toWeb(s) as unknown as ReadableStream<Uint8Array>;
}
